#!/usr/bin/env python3
"""Replace the JP map in V2 (index.html) with native Japanese copy.
Strategy: locate '  jp: {' ... '  kr: {' and replace everything in between.
The KR block and everything after is left completely untouched.
"""

NEW_JP = """  jp: {
    "lang.review": "本書のJP表記はネイティブが精査しております。秋山様へのご提示前に最終確認をお願いいたします。",
    "banner.lockup": "SUNG —1975— · UAE事業提案",
    "banner.line": "ドバイへ。<br/><em>ドバイを起点に、西側市場へ。</em>",
    "hero.eyebrow": "SUNG —1975— · UAE & GCC市場参入 · 機密",
    "hero.h1": "<span class=\\"lockup\\">SUNG —1975—</span>ドバイから始め、<br/>そこから世界に届ける提案。",
    "hero.lede": "ご提案先: <strong>秋山成勲 様 / Choo Sung-hoon</strong> · 提案者: Balraj Singh Kalra、山田さん · ご縁をいただいた <strong>若林涼 様</strong>に、深く感謝申し上げます。",
    "hero.intro-note": "<strong>本書についてのご説明 —</strong> スライドショーではなく、実務用の作業提案書として構成しております。各章は下記の目次から個別にご覧いただけます。本版の数値はすべて2026年5月18日時点の公開市場データ（Social Blade、Grand View Research、Deep Market Insights、各ブランドのプレスリリース）に基づいており、出典は本文中に明示しています。",
    "cover.lockup": "SUNG —1975—",
    "cover.headline": "湾岸へ。",
    "cover.sub": "韓国系日本人アスレジャーブランド「SUNG1975」のUAE・GCC市場参入に向けたご提案。",
    "cover.prepared-for": "ご提案先",
    "cover.prepared-for-val": "秋山成勲 様 / Choo Sung-hoon",
    "cover.prepared-by": "提案者",
    "cover.prepared-by-val": "Balraj Singh Kalra<br/>山田さん（Portgate代表）",
    "cover.meeting": "ミーティング",
    "cover.meeting-val": "ビデオ会議 60分 · 2026年5月",
    "cover.status": "ステータス",
    "cover.status-val": "機密 · v2",
    "part.1": "第1部 · プロジェクトとチーム",
    "part.2": "第2部 · なぜドバイ、なぜ今",
    "part.3": "第3部 · 参入の構造",
    "part.4": "第4部 · 製品",
    "part.5": "第5部 · MMA × ドバイ",
    "part.6": "第6部 · スキンケア",
    "part.7": "第7部 · 最初の30日",
    "sec.1-1.h2": "この提案を、一枚に。",
    "sec.1-2.h2": "<span class=\\"num\\">1.2</span>ご提案を担うチーム。",
    "sec.1-3.h2": "<span class=\\"num\\">1.3</span>秋山様が持つリーチ。",
    "sec.1-4.h2": "<span class=\\"num\\">1.4</span>4フェーズ計画。",
    "sec.2-1.h2": "市場はすでにここにある。そして、まだ誰も本気で狙っていない。",
    "sec.2-2.h2": "<span class=\\"num\\">2.2</span>Giving Movement — 最も近い先例。",
    "sec.2-3.h2": "<span class=\\"num\\">2.3</span>オーディエンスの空白 — ドバイがそれを埋める理由。",
    "sec.2-4.h2": "<span class=\\"num\\">2.4</span>GCCにおける韓国ブランドの軌跡。",
    "sec.3-1.h2": "参入の形は、3つあります。",
    "sec.3-2.h2": "<span class=\\"num\\">3.2</span>役割の分担。",
    "sec.3-3.h2": "<span class=\\"num\\">3.3</span>UAE法人設立 — Portgateが担う範囲。",
    "sec.4-1.h2": "価格はすでに実証されています。",
    "sec.4-2.h2": "<span class=\\"num\\">4.2</span>UAE限定カプセル。",
    "sec.4-3.h2": "<span class=\\"num\\">4.3</span>ビルボード・コンセプト。",
    "sec.5-1.h2": "ファイトカレンダーは止まらない。",
    "sec.5-2.h2": "<span class=\\"num\\">5.2</span>イベント・アクセス — 核となる3つの接点。",
    "sec.5-3.h2": "<span class=\\"num\\">5.3</span>ローンチの瞬間 — 秋山様 × Kris Fade。",
    "sec.5-4.h2": "<span class=\\"num\\">5.4</span>Warehouse Gym — 開設可能なポップアップ拠点。",
    "sec.6-1.h2": "第二のカテゴリ。同じプレイブック、別の棚。",
    "sec.6-2.h2": "<span class=\\"num\\">6.2</span>GCC男性向けK-beautyの実績。",
    "sec.7-1.h2": "ご承認後の最初の30日間。",
    "sec.7-2.h2": "<span class=\\"num\\">7.2</span>連絡先。",
    "footer.left": "SUNG —1975— · UAE提案書 · v2 · 2026-05-18 · 機密",
    "footer.right": "提案者: Balraj Singh Kalra + 山田さん · 紹介: 若林涼 様",

    "sec.1-1.sub": "私どもがお願いすること、私どもが持ち込むもの、秋山様にご許諾いただきたいこと。",
    "sec.1-1.card.h3": "<span class=\\"num\\">1.1</span>SUNG1975について",
    "sec.1-1.card.p1": "SUNG1975は、<strong>秋山成勲 様 / Choo Sung-hoon</strong>によるアスレジャーブランドです。2022年5月にローンチ。日本での小売価格は1点$75〜$156（米ドル）とプレミアム帯に位置し、韓国・日本それぞれのDTC直営店、Musinsa（2024年1月入店）、および2026年5月現在も継続する東京ポップアップで展開されています。",
    "sec.1-1.card.p2": "ブランドには、設計されたデザイン言語と、証明された価格帯と、個人チャンネルで286万人にリーチするファウンダーが揃っています。まだ揃っていないのは、東アジア以外での本格的な市場浸透です。",
    "sec.1-1.card.p3": "本提案は、SUNG1975のUAE・GCC事業を、独占ライセンスのもと私どもが全額拠出・全責任で運営・構築するものです。ドバイをローンチパッドとし、これまでブランドが届いていなかった欧米およびMENA市場への入口といたします。",
    "sec.1-1.pillar.brand.tag": "ブランド",
    "sec.1-1.pillar.brand.h4": "プレミアム・アスレジャー",
    "sec.1-1.pillar.brand.p": "ALO、Lululemon、Vuori、Giving Movementと同じ棚に立てる。",
    "sec.1-1.pillar.personality.tag": "パーソナリティ",
    "sec.1-1.pillar.personality.h4": "秋山様が、ブランドそのもの",
    "sec.1-1.pillar.personality.p": "ファウンダーがブランドそのもの。『Physical: 100』による国際的な認知。",
    "sec.1-1.pillar.market.tag": "市場",
    "sec.1-1.pillar.market.h4": "UAE + GCC",
    "sec.1-1.pillar.market.p": "アスレジャー市場132.6億ドル。2033年までCAGR 9.71%。",
    "sec.1-1.pillar.ask.tag": "お願い",
    "sec.1-1.pillar.ask.h4": "資金ではなく、ライセンスを",
    "sec.1-1.pillar.ask.p": "資本は私どもが拠出。秋山様には、権利のご許諾をいただくだけです。",
    "sec.1-1.catalog.h3": "現行カタログ。",
    "sec.1-1.catalog.sub": "2026年5月18日時点で日本・韓国ストアから取得した、現行SSシーズンのラインナップ。",
    "sec.1-1.product.bonded-hoodie": "ボンディッド・フーディ",
    "sec.1-1.product.raw-patch-tank": "ロウパッチ・タンク",
    "sec.1-1.product.terry-pants": "テリー・テーパード・パンツ",
    "sec.1-1.product.pile-hoodie": "パイル・フーディ",
    "sec.1-1.catalog.src": "sung1975japanshop.com · sung1975w.com · 2026-05-18時点の取得データ",

    "sec.1-2.sub": "ドバイの実務者2名 · 東京のクリエイティブエージェンシー1社 · 格闘技分野の核となる接点1件。",
    "sec.1-2.th.role": "役割",
    "sec.1-2.th.person": "人物 / 法人",
    "sec.1-2.th.function": "機能",
    "sec.1-2.row1.role": "共同創業者 · UAE運営",
    "sec.1-2.row1.person": "<strong>Balraj Singh Kalra</strong>",
    "sec.1-2.row1.function": "ドバイ在住5年。AYUVA（ラグジュアリー・ウェルネス施設）をはじめドバイ複数事業の運営者。UAE現地のオペレーション、フルフィルメント基盤、ジム・空港リレーションを保有。",
    "sec.1-2.row2.role": "共同創業者 · 日本 & ブランド",
    "sec.1-2.row2.person": "<strong>山田さん</strong> · Portgate代表",
    "sec.1-2.row2.function": "ドバイ在住5年。元サイバーエージェントグループ。Portgate（2022年設立）― 日本企業のUAE進出支援会社。JP顧客40社以上、ドバイに4名チーム。現役MMA選手。Forge × Roger Gracie チームとイベントも共同主催。",
    "sec.1-2.row3.role": "運営会社",
    "sec.1-2.row3.person": "<strong>Portgate</strong> (portgg.com)",
    "sec.1-2.row3.function": "UAE法人設立 · 銀行口座 · トレードライセンス · ビザ · 商標登録 · ブランドマネジメント · 物流 · フルフィルメント。4年の実績、日本語YouTube動画250本以上、ブログ記事170本以上。",
    "sec.1-2.row4.role": "マーケティング / クリエイティブ",
    "sec.1-2.row4.person": "<strong>Soren</strong> (soren.co.jp) · 創業者 山田綾香",
    "sec.1-2.row4.function": "東京拠点の日英バイリンガル・クリエイティブエージェンシー。主なクライアント: ザ・リッツ・カールトン京都、井上克仁シェフズテーブル、ヨーライ和紙。家族ネットワークによるクリエイティブ責任。",
    "sec.1-2.row5.role": "戦略アンカー ― 格闘技",
    "sec.1-2.row5.person": "Forge × Roger Gracie Dubai Academy",
    "sec.1-2.row5.function": "ドバイ屈指の格闘技施設。Roger GracieはBJJのロイヤルファミリー。ドバイMMAイベントサーキット全域への紹介経路を保有。詳細は対面で開示いたします。本書には記載しません。",
    "sec.1-2.row6.role": "戦略アンカー ― 空港リテール",
    "sec.1-2.row6.person": "DXB Duty Freeリレーション",
    "sec.1-2.row6.function": "ドバイ国際空港 ― 単一空港として世界最大規模の免税オペレーション ― に直接アクセス可能。Giving Movementのドバイ限定カプセル売上を支えているのと同じ流通チャネルです。フェーズ3の空港リテールへの入口となります。",
    "sec.1-2.row7.role": "ご紹介",
    "sec.1-2.row7.person": "<strong>若林涼 様</strong>",
    "sec.1-2.row7.function": "心より感謝申し上げます。この提案を秋山様へお繋ぎくださった、信頼できる日本側のリレーションです。",
    "sec.1-2.callout.h3": "このチームが適任である理由 ― 二文で。",
    "sec.1-2.callout.p": "Portgateはすでに日本企業40社以上のUAE参入を実行しており、本提案のプレイブックは「発明」ではなく「製品化」されたものです。Sorenは外注ではなく家族ネットワークによるクリエイティブであり、格闘技分野のアンカー接点により、MMA出自のブランドがGCCに参入する際に唯一意味を持つスポーツチャネルへ即日アクセスできます。",

    "sec.1-3.sub": "ライブ取得済みの実数 ― Social Blade、2026年5月18日時点。YouTubeの伸長は中央日報・朝鮮ビズによる。",
    "sec.1-3.target.ig.label": "Instagram",
    "sec.1-3.target.ig.value": "881,798<span>フォロワー</span>",
    "sec.1-3.target.ig.note": "@akiyamachoo · 個人アカウント",
    "sec.1-3.target.yt.label": "YouTube",
    "sec.1-3.target.yt.value": "+1.98M<span>登録者 · 4ヶ月で</span>",
    "sec.1-3.target.yt.note": "2024年11月の新フォーマット開始以降",
    "sec.1-3.target.yt.src": "朝鮮ビズ · 2025年12月",
    "sec.1-3.target.video.label": "単一動画",
    "sec.1-3.target.video.value": "10.99M<span>再生</span>",
    "sec.1-3.target.video.note": "ホームライフ・フォーマット · コメント7,700件",
    "sec.1-3.target.video.src": "中央日報 · 2025年",
    "sec.1-3.target.eng.label": "エンゲージメント率",
    "sec.1-3.target.eng.value": "21.19%<span>対メガ平均1.5%</span>",
    "sec.1-3.target.eng.note": "メガ・インフルエンサーの中央値は約1.5%",
    "sec.1-3.callout.h3": "視聴層は、想像より若い。",
    "sec.1-3.callout.p": "秋山様は、韓国の「アジョシ・シック（中年の格好良さ）」ムーブメントを象徴する顔です。このムーブメントに紐づくポップアップでは、<strong>来場者の70%が20〜30代</strong>、10%がティーンエイジャー。「シルバーフォックス層のみ」ではなく、ジェネレーションZおよびミレニアル層にきちんと届くオーディエンスです。出典: The Straits Times、2025年3月。",
    "sec.1-3.split.bad.h4": "ブランドが現在リーチしている層",
    "sec.1-3.split.good.h4": "ファウンダーがリーチしている層",
    "sec.1-3.gap": "ブランドとファウンダーのリーチ差は、約<strong>123倍</strong>。この差を埋めることが、本ベンチャーのすべての商業機会です。その起点として、ドバイを選びます。",

    "sec.1-4.sub": "Eコマースのローンチからドバイ・フラッグシップまで24ヶ月。資本と実行はすべて私どもの負担です。",
    "sec.1-4.phase1.num": "Phase 01",
    "sec.1-4.phase1.name": "チャネルをローンチ",
    "sec.1-4.phase1.window": "0〜6ヶ月目",
    "sec.1-4.phase2.num": "Phase 02",
    "sec.1-4.phase2.name": "フロアに乗る",
    "sec.1-4.phase2.window": "6〜12ヶ月目",
    "sec.1-4.phase3.num": "Phase 03",
    "sec.1-4.phase3.name": "都市を獲る",
    "sec.1-4.phase3.window": "12〜18ヶ月目",
    "sec.1-4.phase4.num": "Phase 04",
    "sec.1-4.phase4.name": "独立フラッグシップ",
    "sec.1-4.phase4.window": "2年目以降",
    "sec.1-4.callout.h3": "フェーズ1でお願いすること ― フェーズ1のみ。",
    "sec.1-4.callout.p": "UAE・GCC独占販売ライセンス、合意した卸価格での製品供給、年2〜3回のアクティベーション渡航、UAE限定カプセルへのデザイン承認。資金拠出は不要です。運転資金と実行リスクはすべて私どもが負います。",

    "sec.7-1.sub": "PortgateはUAE法人設立を1〜4週間でエンドツーエンドに完了させます。残りのスプリントはEC構築、初回製品フロー、コンテンツエンジンの立ち上げです。",
    "sec.7-1.step1": "<strong>1週目 ― タームシート。</strong> 高レベルのタームシートをドラフト・締結。独占期間を固定。ロイヤリティ料率と最低発注量の枠組みを業界ベンチマーク（売上正味6〜10% · 5年契約）内で合意。",
    "sec.7-1.step2": "<strong>2週目 ― 法人 + ブランド。</strong> PortgateがUAE法人を設立（DMCCまたはMeydan FZ ― 秋山様とご相談のうえ決定）。UAEおよびGCCで商標出願。銀行口座開設。運営口座が稼働可能な状態へ。",
    "sec.7-1.step3": "<strong>3週目 ― 初回コンテナ計画。</strong> ローンチ前需要に対する初期在庫構成を確定。工場の生産枠を確保。通関と3PLを立ち上げ。",
    "sec.7-1.step4": "<strong>4週目 ― EC + コンテンツのキックオフ。</strong> UAE.aeサイトを稼働。バイリンガル・コンテンツエンジンを始動（Soren）。ソフトローンチ日を設定。最初のMMAイベント出展を確定。",
    "sec.7-1.callout.h3": "並行して進めたいこと ― 数値の精度を上げるために。",
    "sec.7-1.callout.p": "タームシート確定前に: <strong>HypeAuditor</strong>（約$50〜$100）を@akiyamachoo様および関連アカウントで実施し、フォロワーの地理分布とエンゲージメントを検証。<strong>店舗ウォーキング</strong>（ドバイモール + モール・オブ・ジ・エミレーツ + ヤスモール）で競合ブランドの店頭価格をライブ取得。<strong>BackLite Media見積</strong>（シェイク・ザイード・ロードの指定看板枠）を取得。24時間の作業で本書のすべての数値が確定可能になります。",
    "sec.7-2.contact.th.role": "役割",
    "sec.7-2.contact.th.person": "担当者",
    "sec.7-2.contact.th.reach": "連絡先",
    "sec.7-2.contact.row1.role": "UAE運営 · ブランド",
    "sec.7-2.contact.row1.person": "Balraj Singh Kalra",
    "sec.7-2.contact.row1.reach": "balrajsinghkalra@gmail.com · ドバイ",
    "sec.7-2.contact.row2.role": "日本 · ブランド · マーケティング",
    "sec.7-2.contact.row2.person": "山田さん · Portgate代表",
    "sec.7-2.contact.row2.reach": "portgg.com · ドバイ（在住5年）",
    "sec.7-2.contact.row3.role": "クリエイティブ · マーケティング",
    "sec.7-2.contact.row3.person": "山田綾香（Jaz）· Soren創業者",
    "sec.7-2.contact.row3.reach": "soren.co.jp · 東京",
    "sec.7-2.contact.row4.role": "ご紹介者",
    "sec.7-2.contact.row4.person": "若林涼 様",
    "sec.7-2.contact.row4.reach": "—",
    "sec.7-2.quote.p": "「どこに滞在するかではなく、どこに自分の場所があるか、だ。」",
    "sec.7-2.quote.cite": "― 別プロジェクトから借用した一文です。同じ原則がここにも当てはまります。ドバイのSUNG1975は、旗を立てるための拠点ではありません。アジア圏外におけるブランドの「居場所」であり、すでにこの地に根を張る者たちによって築かれます。",

    "sec.2-1.sub": "UAEのアスレジャー市場は、気づけば米国外で世界最も活発なプレミアム・フィットネス市場になっていました。",
    "sec.2-1.target.mkt.label": "UAEアスレジャー市場",
    "sec.2-1.target.mkt.value": "$13.26B<span>2024年</span>",
    "sec.2-1.target.mkt.note": "トップス、ボトムス、フットウェア、アクセサリーを含む",
    "sec.2-1.target.cagr.label": "2033年までのCAGR",
    "sec.2-1.target.cagr.note": "プレミアム帯は市場全体を上回るペースで拡大",
    "sec.2-1.target.dxb.label": "DXB旅客数",
    "sec.2-1.target.dxb.value": "92.3M<span>2024年</span>",
    "sec.2-1.target.dxb.note": "世界最大の国際空港 · 10年連続",
    "sec.2-1.target.ddf.label": "DDF売上",
    "sec.2-1.target.ddf.value": "AED 8.68B<span>2025年</span>",
    "sec.2-1.target.ddf.note": "前年比 +9.85%",
    "sec.2-1.h3": "<span class=\\"num\\">2.1</span>プレミアム・アスレジャーは、すでにここにある ― そしてパートナーの選び方が変わりつつある。",
    "sec.2-1.p1": "過去36ヶ月で、主要なプレミアム・アスレジャーブランドはすべて、ドバイにフラッグシップを開店、あるいは開店を表明しました。各社がどのように参入したかのパターンこそ、この市場における最も重要な戦略シグナルです。",
    "sec.2-1.th.brand": "ブランド",
    "sec.2-1.th.partner": "UAEパートナー",
    "sec.2-1.th.entry": "参入時期 · 出店規模",
    "sec.2-1.row.alo.entry": "2024年2月 · ドバイモール旗艦店（833m²）+ ギャラリア・アル・マリヤ（アブダビ）",
    "sec.2-1.row.lulu.partner": "<strong>マジッド・アル・フッタイム</strong> · Lifestyle",
    "sec.2-1.row.lulu.entry": "2015年 · UAE 6店舗 · 中東 20店舗 · Align Pantは地域内で年間50万本以上販売",
    "sec.2-1.row.gymshark.entry": "2025年1月 · ドバイモール（4,300 sqft）· Leana Deebとのアラビア書道カプセルでローンチ",
    "sec.2-1.row.vuori.entry": "2024年 · モール・オブ・ジ・エミレーツ · 全世界15店舗展開 · 高級隣接ポジション",
    "sec.2-1.row.on.entry": "ドバイモール旗艦店 + THAT Concept Storeでのショップ・イン・ショップ",
    "sec.2-1.row.gm.partner": "自社運営（ドバイ発）",
    "sec.2-1.row.gm.entry": "2020年設立 · 5ヶ国13店舗 · UAE国内8店舗",
    "sec.2-1.tab.src": "出典: Alshaya、MAF、Al Tayerのプレスリリース（2024年2月、2024年1月、2025年1月）· TGM公式ストアロケーター",
    "sec.2-1.callout.h3": "戦略シグナル ― そしてSUNG1975が当てはまる位置。",
    "sec.2-1.callout.p": "パターンは明確です。<strong>プレミアムなデジタルネイティブ・ブランドは、いまAlshaya</strong>（マスマーケットのフランチャイズ運営）を回避し、Al TayerまたはMAF Lifestyle（ラグジュアリー・キュレーション）を選んでいます。GymsharkもVuoriもAl Tayer。ドバイに参入するアスレジャーブランドの新しい標準は、90ブランドを抱える運営会社ではなく、小規模でキュレーションされたパートナーです。私どもはその構造を、日本企業のUAE参入を40回実行してきたPortgateを軸に、SUNG1975のために提案します。",

    "sec.2-2.sub": "1サイトのDTCから5年で5ヶ国13店舗にスケールしたドバイ発のプレミアム・アスレジャー。その軌跡を読むことは、SUNG1975のUAE機会規模を測る最も実用的な作業です。",
    "sec.2-2.target.founded.label": "設立",
    "sec.2-2.target.founded.value": "2020年<span>ドバイ</span>",
    "sec.2-2.target.founded.note": "Dominic Nowell-Barnes",
    "sec.2-2.target.seriesa.label": "シリーズA",
    "sec.2-2.target.seriesa.value": "$15M<span>2022年</span>",
    "sec.2-2.target.seriesa.note": "Knuru + Turmeric Capital",
    "sec.2-2.target.charity.label": "慈善寄付累計",
    "sec.2-2.target.charity.value": "$5.4M+<span>2023年9月時点</span>",
    "sec.2-2.target.charity.note": "1点$4寄付 · 135万点以上の販売を示唆",
    "sec.2-2.target.charity.src": "Arabian Business",
    "sec.2-2.target.retail.label": "リテール展開",
    "sec.2-2.target.retail.value": "13<span>店舗 · 5ヶ国</span>",
    "sec.2-2.target.retail.note": "UAE 8店舗 · DXB Duty Free含む",
    "sec.2-2.target.retail.src": "TGMストアロケーター",
    "sec.2-2.quote.p": "「私たちが犯した失敗の一つは、『よし、米国に行こう』と言ったことです ― でも、まだ自分たちのホームグラウンドを本当に押さえていましたか？人々が大事にするのは文化と関連性。海外ブランドが、私たちが自分たちの地域で持つ多様性への理解で勝つことはできません。」",
    "sec.2-2.quote.cite": "― Rania Masri El Khatib、Giving Movement CEO · シャルジャ・アントレプレナーシップ・フェスティバル、2026年1月31日（Gulf News）",
    "sec.2-2.callout.h3": "教訓 ― そして、これが私どもの提案の核心です。",
    "sec.2-2.callout.p": "Giving Movementの創業者は2025年5月に既存投資家へブランドを売却しました（公表は2026年5月）。新CEOは、コストのかかった米国展開の後、明確にMENA最優先へと舵を切っています。SUNG1975にとっての教訓は一言で言えます: <strong>西側を直接追わない。まずドバイで勝つ。西側はドバイへ来させる。</strong>これが私どもの提案です。",

    "sec.2-3.sub": "秋山様の個人チャンネルはIGとYouTubeで約286万人にリーチ。ブランドのリーチは23,000人。",
    "sec.2-3.p1": "秋山様のオーディエンスは韓国・日本に大きく偏り、東アジアおよび東南アジアにロングテールがあります。西側市場 ― 欧州、北米、MENA ― にはまだ届いていません。<strong>そして、ブランドはまだファウンダーのリーチを継承できていません。</strong>",
    "sec.2-3.p2": "ドバイは、この2つを同時に解決するのに世界で最も効率的な一都市です。英語で運営される街。日本人・韓国人のディアスポラ・コミュニティが相応の規模で存在。欧州からの観光客が通年来訪。GCC圏で最大級の高所得層の集積地。そして、2024年に9,230万人の旅客を処理した世界最大の国際空港ハブです。",
    "sec.2-3.p3": "ドバイとリヤドで地歩を築けば、3つの露出レイヤーが同時に開かれます: GCC居住者、欧州観光客、そして彼らが自国に持ち帰るプレス・サイクル。",
    "sec.2-3.callout.h3": "もう一つ、知っておくべきオーディエンスの実態。",
    "sec.2-3.callout.p": "『Physical: 100』（Netflix、2023年1月）以降の西側オーディエンスの伸びは確かにありますが、公開ソースでは定量化されていません。地理・人口統計の内訳には有料インフルエンサー分析（HypeAuditor、Modash）が必要です ― 通常、一回の取得で$50〜$100。タームシート前にこれを実行することをお勧めします。フェーズ1のマーケティング計画が方向性の仮定ではなく実数に基づいて構築されます。",

    "sec.2-4.sub": "韓国系アスレジャーブランドでUAEに出店した先例は、まだありません。一方、韓国コスメは ― 実績ある現地パートナーシップを通じて ― すでに参入済みです。",
    "sec.2-4.th.brand": "ブランド",
    "sec.2-4.th.partner": "現地パートナー",
    "sec.2-4.th.outcome": "実績",
    "sec.2-4.row.musinsa.outcome": "2022年下半期ローンチ。2025年7月〜2028年6月、Kファッションの公式韓国通商機関に指定。海外平均年成長率260%。",
    "sec.2-4.row.etude.outcome": "2018年UAE参入 · ドバイモール旗艦店 · 10店舗のGCC展開計画、次はクウェートとサウジアラビア。",
    "sec.2-4.row.jkos.outcome": "2025年10月UAEローンチ · カルフールハイパーマーケット + 直営店。",
    "sec.2-4.row.laneige.partner": "—",
    "sec.2-4.row.laneige.outcome": "2024年5月、ドバイモール旗艦店 ― ARミラーと常駐皮膚科医を配置。",
    "sec.2-4.row.katl.brand": "韓国アスレジャー（Xexymix、Andar、Mulawear等）",
    "sec.2-4.row.katl.partner": "なし",
    "sec.2-4.row.katl.outcome": "<strong>UAE小売プレゼンスなし。</strong>中国、台湾、オーストラリア、マレーシアには展開済み ― GCCはスキップ。",
    "sec.2-4.tab.src": "Musinsaニュースルーム（2025年7月）· Images Retail ME（2018年2月）· Apparel Groupプレス（2025年10月）· KED Global · 延世大学リサーチ",
    "sec.2-4.callout.h3": "先行者ウィンドウは開いている。そして期限がある。",
    "sec.2-4.callout.p": "Kビューティは「韓国ブランド × GCC運営者」モデルがUAEで機能することを実証しました。Kファッションには、Musinsa Globalによる制度的バックアップと2028年までの韓国通商指定があります。しかし、棚を獲った韓国アスレジャーブランドは、まだありません。SUNG1975には、クリーンな先行者ウィンドウがあります ― そして、このカテゴリーで誰よりも認知されているファウンダーがいます。",

    "sec.3-1.sub": "下記いずれの構造でも受け入れ可能です。共通する要素: ライセンサーはSUNG1975 Japan、UAE法人がGCCの単独地域ライセンシー。PortgateがUAE法人設立から銀行口座、トレードライセンス、ビザ、商標登録までエンドツーエンドで対応。",
    "sec.3-1.callout.h3": "Sorenについての注記。",
    "sec.3-1.callout.p": "Soren（soren.co.jp）は、山田さんの姉<strong>山田綾香（Jaz）</strong>が創業した東京拠点の日英バイリンガル・クリエイティブ&マーケティングエージェンシーです。主なクライアントはザ・リッツ・カールトン京都、井上克仁氏のシェフズテーブル、ヨーライ和紙。Sorenをチームに含めることで、マーケティング部門を家族ネットワーク内に保ちます ― 同じ水準のケア、同じ説明責任。",
    "sec.3-2.sub": "3つの構造に共通する事項。具体的な数値（年1最低発注量、ロイヤリティ料率、独占期間）は、検証済みの比較データに対してフォローアップの財務通話で確定します。",
    "sec.3-2.split.good.h4": "私どもがコミットすること",
    "sec.3-2.split.bad.h4": "秋山様にご許諾いただきたいこと",
    "sec.3-2.callout.h3": "業界ベンチマーク ― 参考値として。",
    "sec.3-2.callout.p": "プレミアム・アパレルのマスターフランチャイズにおけるロイヤリティ料率は<strong>売上正味の6〜10%</strong>が標準で、最低保証ロイヤリティ付き。独占期間の業界標準は<strong>5年</strong>、更新オプション付き ― MAF × Lululemonが2015年に設定した枠組み。出典: SRP Lawyer、FTC Advisory、Images Retail ME。",
    "sec.3-3.sub": "Portgateの既存サービスライン。すでに40社以上の日本企業のUAE参入で実行済み。",
    "sec.3-3.fact.meydan.label": "Meydan Free Zone",
    "sec.3-3.fact.meydan.note": "ライセンス + フレキシデスク、最短1時間で発行。EC優先ローンチに最適。",
    "sec.3-3.fact.dmcc.label": "DMCC",
    "sec.3-3.fact.dmcc.note": "ライセンス + 必須フレキシデスク。銀行口座開設の評判が最も高く、本土小売向けデュアルライセンス・オプションあり。",
    "sec.3-3.fact.mainland.label": "本土LLC",
    "sec.3-3.fact.mainland.note": "+ Ejariオフィス AED 25〜60K/年。本土での直接販売、2020年12月以降は外資100%所有可能。",
    "sec.3-3.tab.src": "DMCC公式ハブ · WellTax Dubaiアドバイザリー · Naviracorporate · 2026年確立値",
    "sec.3-3.callout.h3": "推奨ルート。",
    "sec.3-3.callout.p": "フェーズ2で本土小売（ジムポップアップ、モール店舗）が予定されているなら<strong>DMCC + デュアルライセンス</strong>。そうでなければEC優先の<strong>Meydan Free Zone</strong>でローンチし、小売収益が正当化された時点で本土ブランチを追加。いずれもPortgateが銀行紹介を含めエンドツーエンド1〜4週間で実行します。",

    "sec.4-1.sub": "SUNG1975はすでに日本価格でUAEに発送可能です。価格を新たに発明するのではなく、既存の価格帯をAEDに置き換え、Lululemon、ALO、Vuori、Giving Movementと同じ棚に乗せます。",
    "sec.4-1.callout.h3": "戦略的なクラスタリング。",
    "sec.4-1.callout.p": "UAEのプレミアム・アスレジャー帯は密に集中しています: ティーシャツ AED 250〜300、フーディ AED 500〜600。この下はマスマーケット（Gymsharkの領域）、上は純粋なラグジュアリー（Off-White、Fear of God）。<strong>SUNG1975の既存日本価格は、Vuori、ALO、Giving Movementと同じ中心位置に着地します。</strong>",
    "sec.4-2.sub": "SUNG1975の既存シルエットに、アラビア書体を重ねます。観光客、居住者、そしてGiving Movementが切り開いた空港リテール・チャネル向けの設計。下記レンダリングは生成モックアップ ― 最終デザインはUAE拠点のアラビア書道家に、クレジットを付して委託します。",
    "sec.4-2.capsule.label": "UAE Edition · コンセプトモックアップ",
    "sec.4-2.capsule.h3": "アラビア書道。SUNG1975のミニマリズム。",
    "sec.4-2.capsule.sub": "明確な文化的配慮ガイドラインのもとGemini Imagenで生成 ― 宗教的書体は使わず、モダンなエディトリアル系アラビアのみ。下記6パターンで配置と用語の選択肢を示します。最終委託はUAE拠点のアラビア書道家へ。",
    "sec.4-2.callout.h3": "なぜこのカプセル戦略がすでに実証されているのか。",
    "sec.4-2.callout.p": "この市場で成功するプレミアム・レーベルはすべて、UAEコード化されたカプセルをいずれ投入します。<strong>Nike</strong>はドバイモール旗艦店で、エジプトのアーティスト Mohamed Samir にアラビア幾何書体を委託。<strong>Gymshark</strong>は初の海外常設店（ドバイモール、2025年1月）をアラビア書道カプセルでローンチ。<strong>Louis Vuitton × Nada Debs</strong>の「LV Mirage」はマシュラビーヤ・パターンを採用。<strong>Giving Movementの「Born in Dubai」</strong>はカプセルではなくコアラインです。プレイブックは機能しています。私どもはそれを尊重します。",
    "sec.4-3.sub": "ドバイ・フレーム近くのシェイク・ザイード・ロード。秋山様のお顔。SUNG1975のラテン文字 + アラビア書体のバイリンガルロックアップ。タグラインはブランド自身の創業スローガン。",
    "sec.4-3.bb.label": "コンセプト · シェイク・ザイード・ロード",
    "sec.4-3.bb.h3": "絶え間ない挑戦。<em style=\\"font-style:italic; color:var(--accent-deep)\\">تحدّي مستمر</em>",
    "sec.4-3.bb.sub": "ブランドの既存スローガンの訳。SUNG1975の創業哲学「끊임없는 도전」（끝なき挑戦）は、アラビア語と英語に直接訳出可能。ビルボードは3言語で成立し、コピーをでっち上げる必要がありません。",
    "sec.4-3.bb.placeholder": "ここにGeminiレンダーを挿入予定<br/>プロンプト + 参照画像は /billboard-prompt.html に準備済み<br/>ヒーロー写真 + Samsung × Dubai Frame 参照で実行",
    "sec.4-3.callout.h3": "コストの現実 ― 取引数値の会話のために。",
    "sec.4-3.callout.p": "シェイク・ザイード・ロードのプレミアム静止ビルボードは<strong>月額 AED 225K〜1M（$61K〜$272K）</strong>。デジタルLEDタイプは月額 AED 80K〜400K。これがフェーズ2予算項目の財務的ベースラインであり、初年度最低発注量コミットの基準となります。出典: DataMySite、Lovin Dubai、DNA UAE。",

    "sec.5-1.sub": "UAEは現在、東半球における格闘技の中心地です。UFC、UAE Warriors、Brave CF ― エティハド・アリーナとADNECで通年プロイベントが開催。MMA出自のブランドにとって、この市場で最も価値のある単一のマーケティング・チャネルです。",
    "sec.5-2.sub": "MMAプロモーションへのルート（UFC / UAEW / Brave）は予算があれば誰でも開けます。下記のリレーションシップは、私どもが実際に保有しているものです。",
    "sec.5-3.sub": "秋山様がドバイに到着された瞬間、ブランドのローンチには、その到着をバイラルな出来事に変換する唯一のドバイ生まれのメディア・ボイスが必要です。それは1人で十分です ― ロックインはNetflixの重なりだけではなく、Fade氏が何年もかけて静かに築いてきたフィットネス・レイヤーにあります。",
    "sec.5-4.sub": "ドバイで最もデザイン志向の高いプレミアム・ジム・チェーン ― <em>Dezeen</em>と<em>Wallpaper*</em>に建築が掲載され、市内に8店舗。ウォームな紹介経路があり、最初のミーティングは私どもの側で組みます。",

    "sec.6-1.sub": "TWENTY FIFTY × SUNG 1975 EDITIONは、私どもがこの市場で見た中で最もご提案に完璧な製品です。アパレルが軌道に乗ったフェーズ3で並行投入 ― 同じUAE法人、同じチャネルで。",
    "sec.6-1.callout.h3": "なぜ秋山様 × K-ビューティが固有なのか。",
    "sec.6-1.callout.p": "湾岸の男性向けグルーミング市場は急成長中ですが、製品在庫のほとんどは女性主導のチャネルから派生しています。<strong>MMAの遺産</strong>を背景にした韓国男性向けスキンケアブランドは、湾岸男性が「ご褒美」ではなく「ルーティン」として購入できる、文化的に明確な許可を提供します。棚の他のすべてが解決できていない構造的な摩擦を、これが解きほぐします。",
    "sec.6-2.sub": "湾岸男性向けグルーミング市場と韓国スキンケアの重なりは、機会の量を裏付ける検証済みデータです。",
    "sec.6-2.target.gulf.label": "GCC男性グルーミング",
    "sec.6-2.target.gulf.value": "$3.8B<span>2025年</span>",
    "sec.6-2.target.gulf.note": "サウジアラビア + UAE主導",
    "sec.6-2.target.gulf.src": "Statista 2025",
    "sec.6-2.target.kbeauty.label": "K-ビューティ世界市場",
    "sec.6-2.target.kbeauty.value": "$13.9B<span>2027年予測</span>",
    "sec.6-2.target.kbeauty.note": "CAGR 10.9% · 男性向けが最速成長セグメント",
    "sec.6-2.target.kbeauty.src": "Korea Trade Centre",
    "sec.6-2.target.akito.label": "秋山様 × TWENTY FIFTY",
    "sec.6-2.target.akito.value": "発売中<span>JP公式</span>",
    "sec.6-2.target.akito.note": "ナノファイバー・コラーゲンシート",
    "sec.6-2.target.akito.src": "twenty-fifty.net",
    "sec.6-2.callout.h3": "フェーズ3における並行軸の意義。",
    "sec.6-2.callout.p": "TWENTY FIFTY × SUNG 1975のスキンケア・コラボは、独立した商業性が高いだけでなく、SUNG1975ブランドにとってアパレル単独の場合より顧客生涯価値（LTV）を最大化する「繰り返し購入」のレールを敷きます。アパレルが認知を作り、スキンケアが反復売上を作る。空港リテールでは2つが組み合わさり、AOV（平均注文単価）を大きく押し上げます。",

    "sec.5-1.callout.h3": "スコアリング凡例。",
    "sec.5-1.callout.p": "<strong>3</strong> ― 直接の実務関係 · 共創可能、単なる予約ではない。<strong>2</strong> ― 既存接点を通じたコラボレーション可能。<strong>1</strong> ― 名前のみ、誰でも予約可能な有料ブース・スポンサールート。",
    "sec.5-2.callout.h3": "3. 戦略アンカー ― ドバイ格闘技施設。",
    "sec.5-2.callout.p": "ドバイ屈指のMMA・BJJ施設である<strong>The Forge Gym × Roger Gracie Dubai Academy</strong>のチームと直接の実務関係を持ちます。<em>Roger Gracie</em>はBJJのロイヤル（グレイシー一族 · 複数回の世界王者）。このアンカー関係により、（a）地域カードでのブース配置、（b）ファイトコミュニティ全体への紹介、（c）共同主催イベントが解錠されます。<strong>個人名は対面で開示いたします。本書には記載しません。</strong>",
    "sec.5-3.callout.h3": "一度の訪問。3つのソーシャル発信型アーンドメディア・モーメント。広告費ゼロ。",
    "sec.5-3.callout.p": "ドバイのアスレジャー棚におけるどの競合も再現できないローンチ・メカニズムです。Giving Movement、lululemon、Gymshark ― ドバイのラジオホスト AND Netflixオーディエンス AND 286万人の個人チャンネルで認知を引き出せる顔を持つファウンダーは、誰一人いません。<strong>Kris Fadeコラボが、秋山様の最初のドバイ訪問をブランドのバイラル・ローンチに変える鍵です。</strong>",
    "sec.5-4.callout.h3": "誠実マーカー ― 今日の確定事項、これから確定する事項。",
    "sec.5-4.callout.p": "<strong>確定:</strong> Warehouse Gymリーダーシップとのウォームな実務接続。最初のミーティングは私どもの側で組みます。<strong>そのミーティングで決めること:</strong> 旗艦支店の選定、アクティベーション・カレンダー、カプセル収益分配、独占期間。私どもはアイデアを持ち込み、彼らは耳を傾ける用意があります。本書のコミットは、契約締結ではなく、この会話が最初の30日で発生することです。",
    "sec.6-1.card.h3": "<span class=\\"num\\">6.1</span>すでに存在しているコラボレーション。",
    "sec.6-1.card.p1": "<strong>TWENTY FIFTY × SUNG 1975 EDITION</strong> ― Premium Nano Collagen Sheet × Mist。韓国のナノファイバー・スキンケアブランドTWENTY FIFTY（twenty-fifty.net）との既存コラボです。ブランド名の意味は文字通り「50歳でも20歳の肌と精神を保つ」 ― 51歳の秋山様にとって、設計されたようなフィット。",
    "sec.6-1.card.p2": "製品は本物のプレミアム: 韓国特許のナノファイバーシート技術 + フランス産低分子フィッシュ・コラーゲン。現在の販売は日本国内のみ。機会はフェーズ3で、これをUAE法人に重ね、アパレルの空港リテールと並列で展開することです。",
    "sec.6-2.proven.h3": "UAEにおけるK-ビューティはすでに実証済み ― 現地運営パートナーシップを通じて。",
    "sec.6-2.proven.p": "<strong>Laneige</strong>は2024年5月にドバイモール旗艦店をオープン、ARミラーと常駐皮膚科医を配置。<strong>Beauty of Joseon、COSRX、Sulwhasoo</strong>はWatsons、Sephora ME、Boots、Bloomingdale's経由で流通。<strong>JKOSMEC</strong>は2025年10月にApparel Group経由でCarrefourからUAEローンチ。<strong>KUNDAL</strong>はハラルK-ビューティ・ヘアラインをGCCで2024年1月にローンチ。モデルは機能しています。",
    "sec.6-2.ledomaine.h3": "最も近いセレブリティ・スキンケア比較事例 ― Le Domaine。",
    "sec.6-2.ledomaine.p": "<strong>Le Domaine（ブラッド・ピット × Famille Perrin）</strong>は2022年末ローンチ。価格帯: クレンジング・エマルジョン$80、セラム$385、クリーム$320。流通: フランス、英国、イタリア、ドイツ、スイス、ベネルクス、米国の高級ビューティ・リテーラー。中東はThe Rite Store経由。<strong>意図的に控えめなフレーミング ― 「これはセレブリティ・ブランドではない」</strong> ― は、虚栄ではなく真剣な製品として位置づけたい秋山様のスキンケア・ラインへのプレイブックそのもの。他の実証済み男性セレブリティ・スキンケア参入: Pharrell × Humanrace、Idris Elba × S'able Labs。「MMAレジェンド × 目に見える肌の規律 × 韓国ナノファイバー技術 × GCC男性グルーミングの爆発的成長」の交点は、現時点で誰も占めていないオープン・ホワイトスペース。"
  },
"""

def main():
    path = '/Users/a44/sung1975-uae-pitch/index.html'
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()

    start_marker = '  jp: {'
    end_marker = '  kr: {'

    start_idx = content.find(start_marker)
    if start_idx == -1:
        raise ValueError("Could not find JP map start marker")

    end_idx = content.find(end_marker, start_idx)
    if end_idx == -1:
        raise ValueError("Could not find KR map start marker")

    before = content[:start_idx]
    after = content[end_idx:]

    new_content = before + NEW_JP + after

    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"Done. Replaced {end_idx - start_idx} chars with {len(NEW_JP)} chars.")
    print(f"File size: {len(new_content)} chars")

if __name__ == '__main__':
    main()
